[package]
name = "sailfish"
version = "0.2.2"
authors = ["Ryohei Machida <orcinus4627@gmail.com>"]
description = "Really fast, intuitive template engine for Rust"
homepage = "https://github.com/Kogia-sima/sailfish"
repository = "https://github.com/Kogia-sima/sailfish"
readme = "../README.md"
keywords = ["markup", "template", "html"]
categories = ["template-engine"]
license = "MIT"
workspace = ".."
edition = "2018"

[features]
default = ["derive", "perf-inline"]
derive = ["sailfish-macros"]
perf-inline = []

[dependencies]
itoap = "0.1.0"
ryu = "1.0.4"

[dependencies.sailfish-macros]
path = "../sailfish-macros"
version = "0.2.2"
optional = true

[build-dependencies]
version_check = "0.9.2"
