[package]
name = "examples"
version = "0.0.1"
authors = ["Ryohei Machida <orcinus4627@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
sailfish = { path = "../sailfish" }
sailfish-macros = { path = "../sailfish-macros" }

[[bin]]
name = "simple"
path = "simple.rs"
test = false

[[bin]]
name = "include"
path = "include.rs"
test = false
