name: building github pages documentation

on:
  workflow_dispatch:
  push:
    branches:
      - stable

jobs:
  build-and-deploy:
    name: building documentation and deploying it on gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: pull the code
        uses: actions/checkout@v3
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: build and deploy
        run: mkdocs gh-deploy -f docs/en/mkdocs.yml --force
